const routes = {
    Login: 'Login',
    Register: 'Register',
    SmsVerification: 'SmsVerification',
    BottomTab: 'BottomTab',
    LoginStack: 'LoginStack',
    Home: 'Home',
    Chats: 'Chats',
    Profile: 'Profile',
    Settings: 'Settings',
    MyPets: 'MyPets',
    AddPetSelect: 'AddPetSelect',
    AddPetName: 'AddPetName',
    AddPetKind: 'AddPetKind',
    AddPetGender: 'AddPetGender',
    AddPetPhoto: 'AddPetPhoto',
    AddPetFavoriteGame: 'AddPetFavoriteGame',
    AddPetStarilization: 'AddPetStarilization',
    AddPetAge: 'AddPetAge',
    AddPetSucces: 'AddPetSucces',
    PetDetails: 'PetDetails',
    Premium: 'Premium',
    Comments: 'Comments',
    Ads: 'Ads',
    OtelsList: 'OtelsList',
    Vets: 'Vets',
    PetFilter: 'PetFilter',
    Search: 'Search',
    EditProfile: 'EditProfile',
    LiveChat: 'LiveChat',
    ChangeProfile: 'ChangeProfile',
    Onboarding: 'Onboarding',
    UserRegister: 'UserRegister',
    UserProfile: 'UserProfile',
    Hotels: 'Hotels',
    Welcome: 'Welcome',
    SignUp1: 'SignUp1',
    ImageCarousel: 'ImageCarousel',
    VeterinaryRegister: 'VeterinaryRegister',
    HotelRegister: 'HotelRegister',
    MatchingTab: 'MatchingTab'
}

export default routes
